pub const UNASSIGNED: &str = "UNASSIGNED";
pub const BASIC_LATIN: &str = "BASIC LATIN";
pub const LATIN_1_SUPPLEMENT: &str = "LATIN 1 SUPPLEMENT";
pub const LATIN_EXTENDED_A: &str = "LATIN EXTENDED A";
pub const LATIN_EXTENDED_B: &str = "LATIN EXTENDED B";
pub const IPA_EXTENSIONS: &str = "IPA EXTENSIONS";
pub const SPACING_MODIFIER_LETTERS: &str = "SPACING MODIFIER LETTERS";
pub const COMBINING_DIACRITICAL_MARKS: &str = "COMBINING DIACRITICAL MARKS";
pub const GREEK: &str = "GREEK";
pub const CYRILLIC: &str = "CYRILLIC";
pub const CYRILLIC_SUPPLEMENTARY: &str = "CYRILLIC SUPPLEMENTARY";
pub const ARMENIAN: &str = "ARMENIAN";
pub const HEBREW: &str = "HEBREW";
pub const ARABIC: &str = "ARABIC";
pub const SYRIAC: &str = "SYRIAC";
pub const ARABIC_SUPPLEMENT: &str = "ARABIC SUPPLEMENT";
pub const THAANA: &str = "THAANA";
pub const NKO: &str = "NKO";
pub const SAMARITAN: &str = "SAMARITAN";
pub const MANDAIC: &str = "MANDAIC";
pub const SYRIAC_SUPPLEMENT: &str = "SYRIAC SUPPLEMENT";
pub const ARABIC_EXTENDED_B: &str = "ARABIC EXTENDED B";
pub const ARABIC_EXTENDED_A: &str = "ARABIC EXTENDED A";
pub const DEVANAGARI: &str = "DEVANAGARI";
pub const BENGALI: &str = "BENGALI";
pub const GURMUKHI: &str = "GURMUKHI";
pub const GUJARATI: &str = "GUJARATI";
pub const ORIYA: &str = "ORIYA";
pub const TAMIL: &str = "TAMIL";
pub const TELUGU: &str = "TELUGU";
pub const KANNADA: &str = "KANNADA";
pub const MALAYALAM: &str = "MALAYALAM";
pub const SINHALA: &str = "SINHALA";
pub const THAI: &str = "THAI";
pub const LAO: &str = "LAO";
pub const TIBETAN: &str = "TIBETAN";
pub const MYANMAR: &str = "MYANMAR";
pub const GEORGIAN: &str = "GEORGIAN";
pub const HANGUL_JAMO: &str = "HANGUL JAMO";
pub const ETHIOPIC: &str = "ETHIOPIC";
pub const ETHIOPIC_SUPPLEMENT: &str = "ETHIOPIC SUPPLEMENT";
pub const CHEROKEE: &str = "CHEROKEE";
pub const UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS: &str = "UNIFIED CANADIAN ABORIGINAL SYLLABICS";
pub const OGHAM: &str = "OGHAM";
pub const RUNIC: &str = "RUNIC";
pub const TAGALOG: &str = "TAGALOG";
pub const HANUNOO: &str = "HANUNOO";
pub const BUHID: &str = "BUHID";
pub const TAGBANWA: &str = "TAGBANWA";
pub const KHMER: &str = "KHMER";
pub const MONGOLIAN: &str = "MONGOLIAN";
pub const UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED: &str = "UNIFIED CANADIAN ABORIGINAL SYLLABICS EXTENDED";
pub const LIMBU: &str = "LIMBU";
pub const TAI_LE: &str = "TAI LE";
pub const NEW_TAI_LUE: &str = "NEW TAI LUE";
pub const KHMER_SYMBOLS: &str = "KHMER SYMBOLS";
pub const BUGINESE: &str = "BUGINESE";
pub const TAI_THAM: &str = "TAI THAM";
pub const COMBINING_DIACRITICAL_MARKS_EXTENDED: &str = "COMBINING DIACRITICAL MARKS EXTENDED";
pub const BALINESE: &str = "BALINESE";
pub const SUNDANESE: &str = "SUNDANESE";
pub const BATAK: &str = "BATAK";
pub const LEPCHA: &str = "LEPCHA";
pub const OL_CHIKI: &str = "OL CHIKI";
pub const CYRILLIC_EXTENDED_C: &str = "CYRILLIC EXTENDED C";
pub const GEORGIAN_EXTENDED: &str = "GEORGIAN EXTENDED";
pub const SUNDANESE_SUPPLEMENT: &str = "SUNDANESE SUPPLEMENT";
pub const VEDIC_EXTENSIONS: &str = "VEDIC EXTENSIONS";
pub const PHONETIC_EXTENSIONS: &str = "PHONETIC EXTENSIONS";
pub const PHONETIC_EXTENSIONS_SUPPLEMENT: &str = "PHONETIC EXTENSIONS SUPPLEMENT";
pub const COMBINING_DIACRITICAL_MARKS_SUPPLEMENT: &str = "COMBINING DIACRITICAL MARKS SUPPLEMENT";
pub const LATIN_EXTENDED_ADDITIONAL: &str = "LATIN EXTENDED ADDITIONAL";
pub const GREEK_EXTENDED: &str = "GREEK EXTENDED";
pub const GENERAL_PUNCTUATION: &str = "GENERAL PUNCTUATION";
pub const SUPERSCRIPTS_AND_SUBSCRIPTS: &str = "SUPERSCRIPTS AND SUBSCRIPTS";
pub const CURRENCY_SYMBOLS: &str = "CURRENCY SYMBOLS";
pub const COMBINING_MARKS_FOR_SYMBOLS: &str = "COMBINING MARKS FOR SYMBOLS";
pub const LETTERLIKE_SYMBOLS: &str = "LETTERLIKE SYMBOLS";
pub const NUMBER_FORMS: &str = "NUMBER FORMS";
pub const ARROWS: &str = "ARROWS";
pub const MATHEMATICAL_OPERATORS: &str = "MATHEMATICAL OPERATORS";
pub const MISCELLANEOUS_TECHNICAL: &str = "MISCELLANEOUS TECHNICAL";
pub const CONTROL_PICTURES: &str = "CONTROL PICTURES";
pub const OPTICAL_CHARACTER_RECOGNITION: &str = "OPTICAL CHARACTER RECOGNITION";
pub const ENCLOSED_ALPHANUMERICS: &str = "ENCLOSED ALPHANUMERICS";
pub const BOX_DRAWING: &str = "BOX DRAWING";
pub const BLOCK_ELEMENTS: &str = "BLOCK ELEMENTS";
pub const GEOMETRIC_SHAPES: &str = "GEOMETRIC SHAPES";
pub const MISCELLANEOUS_SYMBOLS: &str = "MISCELLANEOUS SYMBOLS";
pub const DINGBATS: &str = "DINGBATS";
pub const MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A: &str = "MISCELLANEOUS MATHEMATICAL SYMBOLS A";
pub const SUPPLEMENTAL_ARROWS_A: &str = "SUPPLEMENTAL ARROWS A";
pub const BRAILLE_PATTERNS: &str = "BRAILLE PATTERNS";
pub const SUPPLEMENTAL_ARROWS_B: &str = "SUPPLEMENTAL ARROWS B";
pub const MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B: &str = "MISCELLANEOUS MATHEMATICAL SYMBOLS B";
pub const SUPPLEMENTAL_MATHEMATICAL_OPERATORS: &str = "SUPPLEMENTAL MATHEMATICAL OPERATORS";
pub const MISCELLANEOUS_SYMBOLS_AND_ARROWS: &str = "MISCELLANEOUS SYMBOLS AND ARROWS";
pub const GLAGOLITIC: &str = "GLAGOLITIC";
pub const LATIN_EXTENDED_C: &str = "LATIN EXTENDED C";
pub const COPTIC: &str = "COPTIC";
pub const GEORGIAN_SUPPLEMENT: &str = "GEORGIAN SUPPLEMENT";
pub const TIFINAGH: &str = "TIFINAGH";
pub const ETHIOPIC_EXTENDED: &str = "ETHIOPIC EXTENDED";
pub const CYRILLIC_EXTENDED_A: &str = "CYRILLIC EXTENDED A";
pub const SUPPLEMENTAL_PUNCTUATION: &str = "SUPPLEMENTAL PUNCTUATION";
pub const CJK_RADICALS_SUPPLEMENT: &str = "CJK RADICALS SUPPLEMENT";
pub const KANGXI_RADICALS: &str = "KANGXI RADICALS";
pub const IDEOGRAPHIC_DESCRIPTION_CHARACTERS: &str = "IDEOGRAPHIC DESCRIPTION CHARACTERS";
pub const CJK_SYMBOLS_AND_PUNCTUATION: &str = "CJK SYMBOLS AND PUNCTUATION";
pub const HIRAGANA: &str = "HIRAGANA";
pub const KATAKANA: &str = "KATAKANA";
pub const BOPOMOFO: &str = "BOPOMOFO";
pub const HANGUL_COMPATIBILITY_JAMO: &str = "HANGUL COMPATIBILITY JAMO";
pub const KANBUN: &str = "KANBUN";
pub const BOPOMOFO_EXTENDED: &str = "BOPOMOFO EXTENDED";
pub const CJK_STROKES: &str = "CJK STROKES";
pub const KATAKANA_PHONETIC_EXTENSIONS: &str = "KATAKANA PHONETIC EXTENSIONS";
pub const ENCLOSED_CJK_LETTERS_AND_MONTHS: &str = "ENCLOSED CJK LETTERS AND MONTHS";
pub const CJK_COMPATIBILITY: &str = "CJK COMPATIBILITY";
pub const CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A: &str = "CJK UNIFIED IDEOGRAPHS EXTENSION A";
pub const YIJING_HEXAGRAM_SYMBOLS: &str = "YIJING HEXAGRAM SYMBOLS";
pub const CJK_UNIFIED_IDEOGRAPHS: &str = "CJK UNIFIED IDEOGRAPHS";
pub const YI_SYLLABLES: &str = "YI SYLLABLES";
pub const YI_RADICALS: &str = "YI RADICALS";
pub const LISU: &str = "LISU";
pub const VAI: &str = "VAI";
pub const CYRILLIC_EXTENDED_B: &str = "CYRILLIC EXTENDED B";
pub const BAMUM: &str = "BAMUM";
pub const MODIFIER_TONE_LETTERS: &str = "MODIFIER TONE LETTERS";
pub const LATIN_EXTENDED_D: &str = "LATIN EXTENDED D";
pub const SYLOTI_NAGRI: &str = "SYLOTI NAGRI";
pub const COMMON_INDIC_NUMBER_FORMS: &str = "COMMON INDIC NUMBER FORMS";
pub const PHAGS_PA: &str = "PHAGS PA";
pub const SAURASHTRA: &str = "SAURASHTRA";
pub const DEVANAGARI_EXTENDED: &str = "DEVANAGARI EXTENDED";
pub const KAYAH_LI: &str = "KAYAH LI";
pub const REJANG: &str = "REJANG";
pub const HANGUL_JAMO_EXTENDED_A: &str = "HANGUL JAMO EXTENDED A";
pub const JAVANESE: &str = "JAVANESE";
pub const MYANMAR_EXTENDED_B: &str = "MYANMAR EXTENDED B";
pub const CHAM: &str = "CHAM";
pub const MYANMAR_EXTENDED_A: &str = "MYANMAR EXTENDED A";
pub const TAI_VIET: &str = "TAI VIET";
pub const MEETEI_MAYEK_EXTENSIONS: &str = "MEETEI MAYEK EXTENSIONS";
pub const ETHIOPIC_EXTENDED_A: &str = "ETHIOPIC EXTENDED A";
pub const LATIN_EXTENDED_E: &str = "LATIN EXTENDED E";
pub const CHEROKEE_SUPPLEMENT: &str = "CHEROKEE SUPPLEMENT";
pub const MEETEI_MAYEK: &str = "MEETEI MAYEK";
pub const HANGUL_SYLLABLES: &str = "HANGUL SYLLABLES";
pub const HANGUL_JAMO_EXTENDED_B: &str = "HANGUL JAMO EXTENDED B";
pub const HIGH_SURROGATES: &str = "HIGH SURROGATES";
pub const HIGH_PRIVATE_USE_SURROGATES: &str = "HIGH PRIVATE USE SURROGATES";
pub const LOW_SURROGATES: &str = "LOW SURROGATES";
pub const PRIVATE_USE_AREA: &str = "PRIVATE USE AREA";
pub const CJK_COMPATIBILITY_IDEOGRAPHS: &str = "CJK COMPATIBILITY IDEOGRAPHS";
pub const ALPHABETIC_PRESENTATION_FORMS: &str = "ALPHABETIC PRESENTATION FORMS";
pub const ARABIC_PRESENTATION_FORMS_A: &str = "ARABIC PRESENTATION FORMS A";
pub const VARIATION_SELECTORS: &str = "VARIATION SELECTORS";
pub const VERTICAL_FORMS: &str = "VERTICAL FORMS";
pub const COMBINING_HALF_MARKS: &str = "COMBINING HALF MARKS";
pub const CJK_COMPATIBILITY_FORMS: &str = "CJK COMPATIBILITY FORMS";
pub const SMALL_FORM_VARIANTS: &str = "SMALL FORM VARIANTS";
pub const ARABIC_PRESENTATION_FORMS_B: &str = "ARABIC PRESENTATION FORMS B";
pub const HALFWIDTH_AND_FULLWIDTH_FORMS: &str = "HALFWIDTH AND FULLWIDTH FORMS";
pub const SPECIALS: &str = "SPECIALS";
pub const LINEAR_B_SYLLABARY: &str = "LINEAR B SYLLABARY";
pub const LINEAR_B_IDEOGRAMS: &str = "LINEAR B IDEOGRAMS";
pub const AEGEAN_NUMBERS: &str = "AEGEAN NUMBERS";
pub const ANCIENT_GREEK_NUMBERS: &str = "ANCIENT GREEK NUMBERS";
pub const ANCIENT_SYMBOLS: &str = "ANCIENT SYMBOLS";
pub const PHAISTOS_DISC: &str = "PHAISTOS DISC";
pub const LYCIAN: &str = "LYCIAN";
pub const CARIAN: &str = "CARIAN";
pub const COPTIC_EPACT_NUMBERS: &str = "COPTIC EPACT NUMBERS";
pub const OLD_ITALIC: &str = "OLD ITALIC";
pub const GOTHIC: &str = "GOTHIC";
pub const OLD_PERMIC: &str = "OLD PERMIC";
pub const UGARITIC: &str = "UGARITIC";
pub const OLD_PERSIAN: &str = "OLD PERSIAN";
pub const DESERET: &str = "DESERET";
pub const SHAVIAN: &str = "SHAVIAN";
pub const OSMANYA: &str = "OSMANYA";
pub const OSAGE: &str = "OSAGE";
pub const ELBASAN: &str = "ELBASAN";
pub const CAUCASIAN_ALBANIAN: &str = "CAUCASIAN ALBANIAN";
pub const VITHKUQI: &str = "VITHKUQI";
pub const TODHRI: &str = "TODHRI";
pub const LINEAR_A: &str = "LINEAR A";
pub const LATIN_EXTENDED_F: &str = "LATIN EXTENDED F";
pub const CYPRIOT_SYLLABARY: &str = "CYPRIOT SYLLABARY";
pub const IMPERIAL_ARAMAIC: &str = "IMPERIAL ARAMAIC";
pub const PALMYRENE: &str = "PALMYRENE";
pub const NABATAEAN: &str = "NABATAEAN";
pub const HATRAN: &str = "HATRAN";
pub const PHOENICIAN: &str = "PHOENICIAN";
pub const LYDIAN: &str = "LYDIAN";
pub const SIDETIC: &str = "SIDETIC";
pub const MEROITIC_HIEROGLYPHS: &str = "MEROITIC HIEROGLYPHS";
pub const MEROITIC_CURSIVE: &str = "MEROITIC CURSIVE";
pub const KHAROSHTHI: &str = "KHAROSHTHI";
pub const OLD_SOUTH_ARABIAN: &str = "OLD SOUTH ARABIAN";
pub const OLD_NORTH_ARABIAN: &str = "OLD NORTH ARABIAN";
pub const MANICHAEAN: &str = "MANICHAEAN";
pub const AVESTAN: &str = "AVESTAN";
pub const INSCRIPTIONAL_PARTHIAN: &str = "INSCRIPTIONAL PARTHIAN";
pub const INSCRIPTIONAL_PAHLAVI: &str = "INSCRIPTIONAL PAHLAVI";
pub const PSALTER_PAHLAVI: &str = "PSALTER PAHLAVI";
pub const OLD_TURKIC: &str = "OLD TURKIC";
pub const OLD_HUNGARIAN: &str = "OLD HUNGARIAN";
pub const HANIFI_ROHINGYA: &str = "HANIFI ROHINGYA";
pub const GARAY: &str = "GARAY";
pub const RUMI_NUMERAL_SYMBOLS: &str = "RUMI NUMERAL SYMBOLS";
pub const YEZIDI: &str = "YEZIDI";
pub const ARABIC_EXTENDED_C: &str = "ARABIC EXTENDED C";
pub const OLD_SOGDIAN: &str = "OLD SOGDIAN";
pub const SOGDIAN: &str = "SOGDIAN";
pub const OLD_UYGHUR: &str = "OLD UYGHUR";
pub const CHORASMIAN: &str = "CHORASMIAN";
pub const ELYMAIC: &str = "ELYMAIC";
pub const BRAHMI: &str = "BRAHMI";
pub const KAITHI: &str = "KAITHI";
pub const SORA_SOMPENG: &str = "SORA SOMPENG";
pub const CHAKMA: &str = "CHAKMA";
pub const MAHAJANI: &str = "MAHAJANI";
pub const SHARADA: &str = "SHARADA";
pub const SINHALA_ARCHAIC_NUMBERS: &str = "SINHALA ARCHAIC NUMBERS";
pub const KHOJKI: &str = "KHOJKI";
pub const MULTANI: &str = "MULTANI";
pub const KHUDAWADI: &str = "KHUDAWADI";
pub const GRANTHA: &str = "GRANTHA";
pub const TULU_TIGALARI: &str = "TULU TIGALARI";
pub const NEWA: &str = "NEWA";
pub const TIRHUTA: &str = "TIRHUTA";
pub const SIDDHAM: &str = "SIDDHAM";
pub const MODI: &str = "MODI";
pub const MONGOLIAN_SUPPLEMENT: &str = "MONGOLIAN SUPPLEMENT";
pub const TAKRI: &str = "TAKRI";
pub const MYANMAR_EXTENDED_C: &str = "MYANMAR EXTENDED C";
pub const AHOM: &str = "AHOM";
pub const DOGRA: &str = "DOGRA";
pub const WARANG_CITI: &str = "WARANG CITI";
pub const DIVES_AKURU: &str = "DIVES AKURU";
pub const NANDINAGARI: &str = "NANDINAGARI";
pub const ZANABAZAR_SQUARE: &str = "ZANABAZAR SQUARE";
pub const SOYOMBO: &str = "SOYOMBO";
pub const UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A: &str = "UNIFIED CANADIAN ABORIGINAL SYLLABICS EXTENDED A";
pub const PAU_CIN_HAU: &str = "PAU CIN HAU";
pub const DEVANAGARI_EXTENDED_A: &str = "DEVANAGARI EXTENDED A";
pub const SHARADA_SUPPLEMENT: &str = "SHARADA SUPPLEMENT";
pub const SUNUWAR: &str = "SUNUWAR";
pub const BHAIKSUKI: &str = "BHAIKSUKI";
pub const MARCHEN: &str = "MARCHEN";
pub const MASARAM_GONDI: &str = "MASARAM GONDI";
pub const GUNJALA_GONDI: &str = "GUNJALA GONDI";
pub const TOLONG_SIKI: &str = "TOLONG SIKI";
pub const MAKASAR: &str = "MAKASAR";
pub const KAWI: &str = "KAWI";
pub const LISU_SUPPLEMENT: &str = "LISU SUPPLEMENT";
pub const TAMIL_SUPPLEMENT: &str = "TAMIL SUPPLEMENT";
pub const CUNEIFORM: &str = "CUNEIFORM";
pub const CUNEIFORM_NUMBERS_AND_PUNCTUATION: &str = "CUNEIFORM NUMBERS AND PUNCTUATION";
pub const EARLY_DYNASTIC_CUNEIFORM: &str = "EARLY DYNASTIC CUNEIFORM";
pub const CYPRO_MINOAN: &str = "CYPRO MINOAN";
pub const EGYPTIAN_HIEROGLYPHS: &str = "EGYPTIAN HIEROGLYPHS";
pub const EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS: &str = "EGYPTIAN HIEROGLYPH FORMAT CONTROLS";
pub const EGYPTIAN_HIEROGLYPHS_EXTENDED_A: &str = "EGYPTIAN HIEROGLYPHS EXTENDED A";
pub const ANATOLIAN_HIEROGLYPHS: &str = "ANATOLIAN HIEROGLYPHS";
pub const GURUNG_KHEMA: &str = "GURUNG KHEMA";
pub const BAMUM_SUPPLEMENT: &str = "BAMUM SUPPLEMENT";
pub const MRO: &str = "MRO";
pub const TANGSA: &str = "TANGSA";
pub const BASSA_VAH: &str = "BASSA VAH";
pub const PAHAWH_HMONG: &str = "PAHAWH HMONG";
pub const KIRAT_RAI: &str = "KIRAT RAI";
pub const MEDEFAIDRIN: &str = "MEDEFAIDRIN";
pub const BERIA_ERFE: &str = "BERIA ERFE";
pub const MIAO: &str = "MIAO";
pub const IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION: &str = "IDEOGRAPHIC SYMBOLS AND PUNCTUATION";
pub const TANGUT: &str = "TANGUT";
pub const TANGUT_COMPONENTS: &str = "TANGUT COMPONENTS";
pub const KHITAN_SMALL_SCRIPT: &str = "KHITAN SMALL SCRIPT";
pub const TANGUT_SUPPLEMENT: &str = "TANGUT SUPPLEMENT";
pub const TANGUT_COMPONENTS_SUPPLEMENT: &str = "TANGUT COMPONENTS SUPPLEMENT";
pub const KANA_EXTENDED_B: &str = "KANA EXTENDED B";
pub const KANA_SUPPLEMENT: &str = "KANA SUPPLEMENT";
pub const KANA_EXTENDED_A: &str = "KANA EXTENDED A";
pub const SMALL_KANA_EXTENSION: &str = "SMALL KANA EXTENSION";
pub const NUSHU: &str = "NUSHU";
pub const DUPLOYAN: &str = "DUPLOYAN";
pub const SHORTHAND_FORMAT_CONTROLS: &str = "SHORTHAND FORMAT CONTROLS";
pub const SYMBOLS_FOR_LEGACY_COMPUTING_SUPPLEMENT: &str = "SYMBOLS FOR LEGACY COMPUTING SUPPLEMENT";
pub const MISCELLANEOUS_SYMBOLS_SUPPLEMENT: &str = "MISCELLANEOUS SYMBOLS SUPPLEMENT";
pub const ZNAMENNY_MUSICAL_NOTATION: &str = "ZNAMENNY MUSICAL NOTATION";
pub const BYZANTINE_MUSICAL_SYMBOLS: &str = "BYZANTINE MUSICAL SYMBOLS";
pub const MUSICAL_SYMBOLS: &str = "MUSICAL SYMBOLS";
pub const ANCIENT_GREEK_MUSICAL_NOTATION: &str = "ANCIENT GREEK MUSICAL NOTATION";
pub const KAKTOVIK_NUMERALS: &str = "KAKTOVIK NUMERALS";
pub const MAYAN_NUMERALS: &str = "MAYAN NUMERALS";
pub const TAI_XUAN_JING_SYMBOLS: &str = "TAI XUAN JING SYMBOLS";
pub const COUNTING_ROD_NUMERALS: &str = "COUNTING ROD NUMERALS";
pub const MATHEMATICAL_ALPHANUMERIC_SYMBOLS: &str = "MATHEMATICAL ALPHANUMERIC SYMBOLS";
pub const SUTTON_SIGNWRITING: &str = "SUTTON SIGNWRITING";
pub const LATIN_EXTENDED_G: &str = "LATIN EXTENDED G";
pub const GLAGOLITIC_SUPPLEMENT: &str = "GLAGOLITIC SUPPLEMENT";
pub const CYRILLIC_EXTENDED_D: &str = "CYRILLIC EXTENDED D";
pub const NYIAKENG_PUACHUE_HMONG: &str = "NYIAKENG PUACHUE HMONG";
pub const TOTO: &str = "TOTO";
pub const WANCHO: &str = "WANCHO";
pub const NAG_MUNDARI: &str = "NAG MUNDARI";
pub const OL_ONAL: &str = "OL ONAL";
pub const TAI_YO: &str = "TAI YO";
pub const ETHIOPIC_EXTENDED_B: &str = "ETHIOPIC EXTENDED B";
pub const MENDE_KIKAKUI: &str = "MENDE KIKAKUI";
pub const ADLAM: &str = "ADLAM";
pub const INDIC_SIYAQ_NUMBERS: &str = "INDIC SIYAQ NUMBERS";
pub const OTTOMAN_SIYAQ_NUMBERS: &str = "OTTOMAN SIYAQ NUMBERS";
pub const ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS: &str = "ARABIC MATHEMATICAL ALPHABETIC SYMBOLS";
pub const MAHJONG_TILES: &str = "MAHJONG TILES";
pub const DOMINO_TILES: &str = "DOMINO TILES";
pub const PLAYING_CARDS: &str = "PLAYING CARDS";
pub const ENCLOSED_ALPHANUMERIC_SUPPLEMENT: &str = "ENCLOSED ALPHANUMERIC SUPPLEMENT";
pub const ENCLOSED_IDEOGRAPHIC_SUPPLEMENT: &str = "ENCLOSED IDEOGRAPHIC SUPPLEMENT";
pub const MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS: &str = "MISCELLANEOUS SYMBOLS AND PICTOGRAPHS";
pub const EMOTICONS: &str = "EMOTICONS";
pub const ORNAMENTAL_DINGBATS: &str = "ORNAMENTAL DINGBATS";
pub const TRANSPORT_AND_MAP_SYMBOLS: &str = "TRANSPORT AND MAP SYMBOLS";
pub const ALCHEMICAL_SYMBOLS: &str = "ALCHEMICAL SYMBOLS";
pub const GEOMETRIC_SHAPES_EXTENDED: &str = "GEOMETRIC SHAPES EXTENDED";
pub const SUPPLEMENTAL_ARROWS_C: &str = "SUPPLEMENTAL ARROWS C";
pub const SUPPLEMENTAL_SYMBOLS_AND_PICTOGRAPHS: &str = "SUPPLEMENTAL SYMBOLS AND PICTOGRAPHS";
pub const CHESS_SYMBOLS: &str = "CHESS SYMBOLS";
pub const SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A: &str = "SYMBOLS AND PICTOGRAPHS EXTENDED A";
pub const SYMBOLS_FOR_LEGACY_COMPUTING: &str = "SYMBOLS FOR LEGACY COMPUTING";
pub const CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B: &str = "CJK UNIFIED IDEOGRAPHS EXTENSION B";
pub const CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C: &str = "CJK UNIFIED IDEOGRAPHS EXTENSION C";
pub const CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D: &str = "CJK UNIFIED IDEOGRAPHS EXTENSION D";
pub const CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E: &str = "CJK UNIFIED IDEOGRAPHS EXTENSION E";
pub const CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F: &str = "CJK UNIFIED IDEOGRAPHS EXTENSION F";
pub const CJK_UNIFIED_IDEOGRAPHS_EXTENSION_I: &str = "CJK UNIFIED IDEOGRAPHS EXTENSION I";
pub const CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT: &str = "CJK COMPATIBILITY IDEOGRAPHS SUPPLEMENT";
pub const CJK_UNIFIED_IDEOGRAPHS_EXTENSION_G: &str = "CJK UNIFIED IDEOGRAPHS EXTENSION G";
pub const CJK_UNIFIED_IDEOGRAPHS_EXTENSION_H: &str = "CJK UNIFIED IDEOGRAPHS EXTENSION H";
pub const CJK_UNIFIED_IDEOGRAPHS_EXTENSION_J: &str = "CJK UNIFIED IDEOGRAPHS EXTENSION J";
pub const TAGS: &str = "TAGS";
pub const VARIATION_SELECTORS_SUPPLEMENT: &str = "VARIATION SELECTORS SUPPLEMENT";
pub const SUPPLEMENTARY_PRIVATE_USE_AREA_A: &str = "SUPPLEMENTARY PRIVATE USE AREA A";
pub const SUPPLEMENTARY_PRIVATE_USE_AREA_B: &str = "SUPPLEMENTARY PRIVATE USE AREA B";

pub const BLOCKS: [&'static str; 397] = [
    BASIC_LATIN,
    LATIN_1_SUPPLEMENT,
    LATIN_EXTENDED_A,
    LATIN_EXTENDED_B,
    IPA_EXTENSIONS,
    SPACING_MODIFIER_LETTERS,
    COMBINING_DIACRITICAL_MARKS,
    GREEK,
    CYRILLIC,
    CYRILLIC_SUPPLEMENTARY,
    ARMENIAN,
    HEBREW,
    ARABIC,
    SYRIAC,
    ARABIC_SUPPLEMENT,
    THAANA,
    NKO,
    SAMARITAN,
    MANDAIC,
    SYRIAC_SUPPLEMENT,
    ARABIC_EXTENDED_B,
    ARABIC_EXTENDED_A,
    DEVANAGARI,
    BENGALI,
    GURMUKHI,
    GUJARATI,
    ORIYA,
    TAMIL,
    TELUGU,
    KANNADA,
    MALAYALAM,
    SINHALA,
    THAI,
    LAO,
    TIBETAN,
    MYANMAR,
    GEORGIAN,
    HANGUL_JAMO,
    ETHIOPIC,
    ETHIOPIC_SUPPLEMENT,
    CHEROKEE,
    UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS,
    OGHAM,
    RUNIC,
    TAGALOG,
    HANUNOO,
    BUHID,
    TAGBANWA,
    KHMER,
    MONGOLIAN,
    UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED,
    LIMBU,
    TAI_LE,
    NEW_TAI_LUE,
    KHMER_SYMBOLS,
    BUGINESE,
    TAI_THAM,
    COMBINING_DIACRITICAL_MARKS_EXTENDED,
    BALINESE,
    SUNDANESE,
    BATAK,
    LEPCHA,
    OL_CHIKI,
    CYRILLIC_EXTENDED_C,
    GEORGIAN_EXTENDED,
    SUNDANESE_SUPPLEMENT,
    VEDIC_EXTENSIONS,
    PHONETIC_EXTENSIONS,
    PHONETIC_EXTENSIONS_SUPPLEMENT,
    COMBINING_DIACRITICAL_MARKS_SUPPLEMENT,
    LATIN_EXTENDED_ADDITIONAL,
    GREEK_EXTENDED,
    GENERAL_PUNCTUATION,
    SUPERSCRIPTS_AND_SUBSCRIPTS,
    CURRENCY_SYMBOLS,
    COMBINING_MARKS_FOR_SYMBOLS,
    LETTERLIKE_SYMBOLS,
    NUMBER_FORMS,
    ARROWS,
    MATHEMATICAL_OPERATORS,
    MISCELLANEOUS_TECHNICAL,
    CONTROL_PICTURES,
    OPTICAL_CHARACTER_RECOGNITION,
    ENCLOSED_ALPHANUMERICS,
    BOX_DRAWING,
    BLOCK_ELEMENTS,
    GEOMETRIC_SHAPES,
    MISCELLANEOUS_SYMBOLS,
    DINGBATS,
    MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A,
    SUPPLEMENTAL_ARROWS_A,
    BRAILLE_PATTERNS,
    SUPPLEMENTAL_ARROWS_B,
    MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B,
    SUPPLEMENTAL_MATHEMATICAL_OPERATORS,
    MISCELLANEOUS_SYMBOLS_AND_ARROWS,
    GLAGOLITIC,
    LATIN_EXTENDED_C,
    COPTIC,
    GEORGIAN_SUPPLEMENT,
    TIFINAGH,
    ETHIOPIC_EXTENDED,
    CYRILLIC_EXTENDED_A,
    SUPPLEMENTAL_PUNCTUATION,
    CJK_RADICALS_SUPPLEMENT,
    KANGXI_RADICALS,
    UNASSIGNED,
    IDEOGRAPHIC_DESCRIPTION_CHARACTERS,
    CJK_SYMBOLS_AND_PUNCTUATION,
    HIRAGANA,
    KATAKANA,
    BOPOMOFO,
    HANGUL_COMPATIBILITY_JAMO,
    KANBUN,
    BOPOMOFO_EXTENDED,
    CJK_STROKES,
    KATAKANA_PHONETIC_EXTENSIONS,
    ENCLOSED_CJK_LETTERS_AND_MONTHS,
    CJK_COMPATIBILITY,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A,
    YIJING_HEXAGRAM_SYMBOLS,
    CJK_UNIFIED_IDEOGRAPHS,
    YI_SYLLABLES,
    YI_RADICALS,
    LISU,
    VAI,
    CYRILLIC_EXTENDED_B,
    BAMUM,
    MODIFIER_TONE_LETTERS,
    LATIN_EXTENDED_D,
    SYLOTI_NAGRI,
    COMMON_INDIC_NUMBER_FORMS,
    PHAGS_PA,
    SAURASHTRA,
    DEVANAGARI_EXTENDED,
    KAYAH_LI,
    REJANG,
    HANGUL_JAMO_EXTENDED_A,
    JAVANESE,
    MYANMAR_EXTENDED_B,
    CHAM,
    MYANMAR_EXTENDED_A,
    TAI_VIET,
    MEETEI_MAYEK_EXTENSIONS,
    ETHIOPIC_EXTENDED_A,
    LATIN_EXTENDED_E,
    CHEROKEE_SUPPLEMENT,
    MEETEI_MAYEK,
    HANGUL_SYLLABLES,
    HANGUL_JAMO_EXTENDED_B,
    HIGH_SURROGATES,
    HIGH_PRIVATE_USE_SURROGATES,
    LOW_SURROGATES,
    PRIVATE_USE_AREA,
    CJK_COMPATIBILITY_IDEOGRAPHS,
    ALPHABETIC_PRESENTATION_FORMS,
    ARABIC_PRESENTATION_FORMS_A,
    VARIATION_SELECTORS,
    VERTICAL_FORMS,
    COMBINING_HALF_MARKS,
    CJK_COMPATIBILITY_FORMS,
    SMALL_FORM_VARIANTS,
    ARABIC_PRESENTATION_FORMS_B,
    HALFWIDTH_AND_FULLWIDTH_FORMS,
    SPECIALS,
    LINEAR_B_SYLLABARY,
    LINEAR_B_IDEOGRAMS,
    AEGEAN_NUMBERS,
    ANCIENT_GREEK_NUMBERS,
    ANCIENT_SYMBOLS,
    PHAISTOS_DISC,
    UNASSIGNED,
    LYCIAN,
    CARIAN,
    COPTIC_EPACT_NUMBERS,
    OLD_ITALIC,
    GOTHIC,
    OLD_PERMIC,
    UGARITIC,
    OLD_PERSIAN,
    UNASSIGNED,
    DESERET,
    SHAVIAN,
    OSMANYA,
    OSAGE,
    ELBASAN,
    CAUCASIAN_ALBANIAN,
    VITHKUQI,
    TODHRI,
    LINEAR_A,
    LATIN_EXTENDED_F,
    UNASSIGNED,
    CYPRIOT_SYLLABARY,
    IMPERIAL_ARAMAIC,
    PALMYRENE,
    NABATAEAN,
    UNASSIGNED,
    HATRAN,
    PHOENICIAN,
    LYDIAN,
    SIDETIC,
    UNASSIGNED,
    MEROITIC_HIEROGLYPHS,
    MEROITIC_CURSIVE,
    KHAROSHTHI,
    OLD_SOUTH_ARABIAN,
    OLD_NORTH_ARABIAN,
    UNASSIGNED,
    MANICHAEAN,
    AVESTAN,
    INSCRIPTIONAL_PARTHIAN,
    INSCRIPTIONAL_PAHLAVI,
    PSALTER_PAHLAVI,
    UNASSIGNED,
    OLD_TURKIC,
    UNASSIGNED,
    OLD_HUNGARIAN,
    HANIFI_ROHINGYA,
    GARAY,
    UNASSIGNED,
    RUMI_NUMERAL_SYMBOLS,
    YEZIDI,
    ARABIC_EXTENDED_C,
    OLD_SOGDIAN,
    SOGDIAN,
    OLD_UYGHUR,
    CHORASMIAN,
    ELYMAIC,
    BRAHMI,
    KAITHI,
    SORA_SOMPENG,
    CHAKMA,
    MAHAJANI,
    SHARADA,
    SINHALA_ARCHAIC_NUMBERS,
    KHOJKI,
    UNASSIGNED,
    MULTANI,
    KHUDAWADI,
    GRANTHA,
    TULU_TIGALARI,
    NEWA,
    TIRHUTA,
    UNASSIGNED,
    SIDDHAM,
    MODI,
    MONGOLIAN_SUPPLEMENT,
    TAKRI,
    MYANMAR_EXTENDED_C,
    AHOM,
    UNASSIGNED,
    DOGRA,
    UNASSIGNED,
    WARANG_CITI,
    DIVES_AKURU,
    UNASSIGNED,
    NANDINAGARI,
    ZANABAZAR_SQUARE,
    SOYOMBO,
    UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED_A,
    PAU_CIN_HAU,
    DEVANAGARI_EXTENDED_A,
    SHARADA_SUPPLEMENT,
    UNASSIGNED,
    SUNUWAR,
    BHAIKSUKI,
    MARCHEN,
    UNASSIGNED,
    MASARAM_GONDI,
    GUNJALA_GONDI,
    TOLONG_SIKI,
    UNASSIGNED,
    MAKASAR,
    KAWI,
    UNASSIGNED,
    LISU_SUPPLEMENT,
    TAMIL_SUPPLEMENT,
    CUNEIFORM,
    CUNEIFORM_NUMBERS_AND_PUNCTUATION,
    EARLY_DYNASTIC_CUNEIFORM,
    UNASSIGNED,
    CYPRO_MINOAN,
    EGYPTIAN_HIEROGLYPHS,
    EGYPTIAN_HIEROGLYPH_FORMAT_CONTROLS,
    EGYPTIAN_HIEROGLYPHS_EXTENDED_A,
    ANATOLIAN_HIEROGLYPHS,
    UNASSIGNED,
    GURUNG_KHEMA,
    UNASSIGNED,
    BAMUM_SUPPLEMENT,
    MRO,
    TANGSA,
    BASSA_VAH,
    PAHAWH_HMONG,
    UNASSIGNED,
    KIRAT_RAI,
    UNASSIGNED,
    MEDEFAIDRIN,
    BERIA_ERFE,
    UNASSIGNED,
    MIAO,
    UNASSIGNED,
    IDEOGRAPHIC_SYMBOLS_AND_PUNCTUATION,
    TANGUT,
    TANGUT_COMPONENTS,
    KHITAN_SMALL_SCRIPT,
    TANGUT_SUPPLEMENT,
    TANGUT_COMPONENTS_SUPPLEMENT,
    UNASSIGNED,
    KANA_EXTENDED_B,
    KANA_SUPPLEMENT,
    KANA_EXTENDED_A,
    SMALL_KANA_EXTENSION,
    NUSHU,
    UNASSIGNED,
    DUPLOYAN,
    SHORTHAND_FORMAT_CONTROLS,
    UNASSIGNED,
    SYMBOLS_FOR_LEGACY_COMPUTING_SUPPLEMENT,
    MISCELLANEOUS_SYMBOLS_SUPPLEMENT,
    ZNAMENNY_MUSICAL_NOTATION,
    UNASSIGNED,
    BYZANTINE_MUSICAL_SYMBOLS,
    MUSICAL_SYMBOLS,
    ANCIENT_GREEK_MUSICAL_NOTATION,
    UNASSIGNED,
    KAKTOVIK_NUMERALS,
    MAYAN_NUMERALS,
    TAI_XUAN_JING_SYMBOLS,
    COUNTING_ROD_NUMERALS,
    UNASSIGNED,
    MATHEMATICAL_ALPHANUMERIC_SYMBOLS,
    SUTTON_SIGNWRITING,
    UNASSIGNED,
    LATIN_EXTENDED_G,
    GLAGOLITIC_SUPPLEMENT,
    CYRILLIC_EXTENDED_D,
    UNASSIGNED,
    NYIAKENG_PUACHUE_HMONG,
    UNASSIGNED,
    TOTO,
    WANCHO,
    UNASSIGNED,
    NAG_MUNDARI,
    UNASSIGNED,
    OL_ONAL,
    UNASSIGNED,
    TAI_YO,
    UNASSIGNED,
    ETHIOPIC_EXTENDED_B,
    MENDE_KIKAKUI,
    UNASSIGNED,
    ADLAM,
    UNASSIGNED,
    INDIC_SIYAQ_NUMBERS,
    UNASSIGNED,
    OTTOMAN_SIYAQ_NUMBERS,
    UNASSIGNED,
    ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS,
    UNASSIGNED,
    MAHJONG_TILES,
    DOMINO_TILES,
    PLAYING_CARDS,
    ENCLOSED_ALPHANUMERIC_SUPPLEMENT,
    ENCLOSED_IDEOGRAPHIC_SUPPLEMENT,
    MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS,
    EMOTICONS,
    ORNAMENTAL_DINGBATS,
    TRANSPORT_AND_MAP_SYMBOLS,
    ALCHEMICAL_SYMBOLS,
    GEOMETRIC_SHAPES_EXTENDED,
    SUPPLEMENTAL_ARROWS_C,
    SUPPLEMENTAL_SYMBOLS_AND_PICTOGRAPHS,
    CHESS_SYMBOLS,
    SYMBOLS_AND_PICTOGRAPHS_EXTENDED_A,
    SYMBOLS_FOR_LEGACY_COMPUTING,
    UNASSIGNED,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B,
    UNASSIGNED,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_C,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_D,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_E,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_F,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_I,
    UNASSIGNED,
    CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT,
    UNASSIGNED,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_G,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_H,
    CJK_UNIFIED_IDEOGRAPHS_EXTENSION_J,
    UNASSIGNED,
    TAGS,
    UNASSIGNED,
    VARIATION_SELECTORS_SUPPLEMENT,
    UNASSIGNED,
    SUPPLEMENTARY_PRIVATE_USE_AREA_A,
    SUPPLEMENTARY_PRIVATE_USE_AREA_B,
];

const BLOCK_STARTS: [u32; 397] = [
    0,
    128,
    256,
    384,
    592,
    688,
    768,
    880,
    1024,
    1280,
    1328,
    1424,
    1536,
    1792,
    1872,
    1920,
    1984,
    2048,
    2112,
    2144,
    2160,
    2208,
    2304,
    2432,
    2560,
    2688,
    2816,
    2944,
    3072,
    3200,
    3328,
    3456,
    3584,
    3712,
    3840,
    4096,
    4256,
    4352,
    4608,
    4992,
    5024,
    5120,
    5760,
    5792,
    5888,
    5920,
    5952,
    5984,
    6016,
    6144,
    6320,
    6400,
    6480,
    6528,
    6624,
    6656,
    6688,
    6832,
    6912,
    7040,
    7104,
    7168,
    7248,
    7296,
    7312,
    7360,
    7376,
    7424,
    7552,
    7616,
    7680,
    7936,
    8192,
    8304,
    8352,
    8400,
    8448,
    8528,
    8592,
    8704,
    8960,
    9216,
    9280,
    9312,
    9472,
    9600,
    9632,
    9728,
    9984,
    10176,
    10224,
    10240,
    10496,
    10624,
    10752,
    11008,
    11264,
    11360,
    11392,
    11520,
    11568,
    11648,
    11744,
    11776,
    11904,
    12032,
    12256,
    12272,
    12288,
    12352,
    12448,
    12544,
    12592,
    12688,
    12704,
    12736,
    12784,
    12800,
    13056,
    13312,
    19904,
    19968,
    40960,
    42128,
    42192,
    42240,
    42560,
    42656,
    42752,
    42784,
    43008,
    43056,
    43072,
    43136,
    43232,
    43264,
    43312,
    43360,
    43392,
    43488,
    43520,
    43616,
    43648,
    43744,
    43776,
    43824,
    43888,
    43968,
    44032,
    55216,
    55296,
    56192,
    56320,
    57344,
    63744,
    64256,
    64336,
    65024,
    65040,
    65056,
    65072,
    65104,
    65136,
    65280,
    65520,
    65536,
    65664,
    65792,
    65856,
    65936,
    66000,
    66048,
    66176,
    66208,
    66272,
    66304,
    66352,
    66384,
    66432,
    66464,
    66528,
    66560,
    66640,
    66688,
    66736,
    66816,
    66864,
    66928,
    67008,
    67072,
    67456,
    67520,
    67584,
    67648,
    67680,
    67712,
    67760,
    67808,
    67840,
    67872,
    67904,
    67936,
    67968,
    68000,
    68096,
    68192,
    68224,
    68256,
    68288,
    68352,
    68416,
    68448,
    68480,
    68528,
    68608,
    68688,
    68736,
    68864,
    68928,
    69008,
    69216,
    69248,
    69312,
    69376,
    69424,
    69488,
    69552,
    69600,
    69632,
    69760,
    69840,
    69888,
    69968,
    70016,
    70112,
    70144,
    70224,
    70272,
    70320,
    70400,
    70528,
    70656,
    70784,
    70880,
    71040,
    71168,
    71264,
    71296,
    71376,
    71424,
    71504,
    71680,
    71760,
    71840,
    71936,
    72032,
    72096,
    72192,
    72272,
    72368,
    72384,
    72448,
    72544,
    72576,
    72640,
    72704,
    72816,
    72896,
    72960,
    73056,
    73136,
    73200,
    73440,
    73472,
    73568,
    73648,
    73664,
    73728,
    74752,
    74880,
    75088,
    77712,
    77824,
    78896,
    78944,
    82944,
    83584,
    90368,
    90432,
    92160,
    92736,
    92784,
    92880,
    92928,
    93072,
    93504,
    93568,
    93760,
    93856,
    93920,
    93952,
    94112,
    94176,
    94208,
    100352,
    101120,
    101632,
    101760,
    101888,
    110576,
    110592,
    110848,
    110896,
    110960,
    111360,
    113664,
    113824,
    113840,
    117760,
    118464,
    118528,
    118736,
    118784,
    119040,
    119296,
    119376,
    119488,
    119520,
    119552,
    119648,
    119680,
    119808,
    120832,
    121520,
    122624,
    122880,
    122928,
    123024,
    123136,
    123216,
    123536,
    123584,
    123648,
    124112,
    124160,
    124368,
    124416,
    124608,
    124672,
    124896,
    124928,
    125152,
    125184,
    125280,
    126064,
    126144,
    126208,
    126288,
    126464,
    126720,
    126976,
    127024,
    127136,
    127232,
    127488,
    127744,
    128512,
    128592,
    128640,
    128768,
    128896,
    129024,
    129280,
    129536,
    129648,
    129792,
    130048,
    131072,
    173792,
    173824,
    177984,
    178208,
    183984,
    191472,
    192096,
    194560,
    195104,
    196608,
    201552,
    205744,
    210048,
    917504,
    917632,
    917760,
    918000,
    983040,
    1048576,
];

pub fn block_index(codepoint: u32) -> usize {
    BLOCK_STARTS
        .binary_search(&codepoint)
        .unwrap_or_else(|index| index - 1)
}

pub struct Block {
    pub name: &'static str,
    pub start: u32,
    pub end: u32,
}

impl Block {
    pub fn at(index: usize) -> Self {
        Self {
            name: BLOCKS[index],
            start: BLOCK_STARTS[index],
            end: *BLOCK_STARTS.get(index + 1).unwrap_or(&0x10FFFF),
        }
    }
}
